# Atajos para cambiar posición de MPRIS en Caelestia Shell
bind = ALT SHIFT, 1, exec, caelestia shell mpris position 0.1
bind = ALT SHIFT, 2, exec, caelestia shell mpris position 0.2
bind = ALT SHIFT, 3, exec, caelestia shell mpris position 0.3
bind = ALT SHIFT, 4, exec, caelestia shell mpris position 0.4
bind = ALT SHIFT, 5, exec, caelestia shell mpris position 0.5
bind = ALT SHIFT, 6, exec, caelestia shell mpris position 0.6
bind = ALT SHIFT, 7, exec, caelestia shell mpris position 0.7
bind = ALT SHIFT, 8, exec, caelestia shell mpris position 0.8
bind = ALT SHIFT, 9, exec, caelestia shell mpris position 0.9

# Atajos para cambiar el tamaño de la ventana
binde = Super ALT, right, resizeactive, 20 0
binde = Super ALT, left, resizeactive, -20 0
binde = Super ALT, up, resizeactive, 0 -20
binde = Super ALT, down, resizeactive, 0 20

# Atajos para controlar aplicaciones de android
bind = SUPER SHIFT, W, exec, ~/adb-scripts/launcher.sh whatsapp
bind = SUPER SHIFT, Y, exec, ~/adb-scripts/launcher.sh youtube
bind = SUPER SHIFT, B, exec, ~/adb-scripts/launcher.sh buffer
bind = SUPER SHIFT, H, exec, ~/adb-scripts/launcher.sh home
bind = SUPER SHIFT, G, exec, ~/adb-scripts/launcher.sh go

# Atajos de algunas utilidades
bind = Super, P, fullscreen, 1
bind = Super, I, exec, caelestia shell mpris raise
bind = Super, U, exec,  caelestia shell drawers openPopout tools 0
bind = Super, O, workspace, previouso

# Reset caelestia
bind = Super, G, exec, ~/.config.bak/hypr/resetCaelestia.sh

# Atajos para desplazarse en un workspace 2D
bind = Super Shift, j, exec, ~/.config/hypr/ws-move.sh left
bind = Super Shift, code:47, exec, ~/.config/hypr/ws-move.sh right
bind = Super Shift, k, exec, ~/.config/hypr/ws-move.sh up
bind = Super Shift, l, exec, ~/.config/hypr/ws-move.sh down

# Atajo para moverse en un workspace 2D mediante script
bind = Super Shift, left, exec, ~/.config/hypr/ws-move.sh left
bind = Super Shift, right, exec, ~/.config/hypr/ws-move.sh right
bind = Super Shift, up, exec, ~/.config/hypr/ws-move.sh up
bind = Super Shift, down, exec, ~/.config/hypr/ws-move.sh down

# Mover entre ventanas
bind = Super, j, movefocus, l
bind = Super, code:47, movefocus, r
bind = Super, k, movefocus, u
bind = Super, l, movefocus, d

bind = Super, C, exec, hyprctl --batch "dispatch centerwindow 1"

# Algunas reglas
windowrule = fullscreen_state 1 0, match:class zen

windowrule = match:class thunar, float on
windowrule = match:class thunar, center on
windowrule = match:class thunar, size 900 500

windowrule = match:class xdg-desktop-portal-gtk, float on
windowrule = match:class xdg-desktop-portal-gtk, center on
windowrule = match:class xdg-desktop-portal-gtk, size 900 500